### ISSUE TITLE
Black screen error. 

### ISSUE THREAD

**Issue by oznfc** [updeshxp/scrcpy-android#8]
Hi . I deployed app  from android studio to my device. When ı tryed connect to another device from app  , ı can see only black screen . It's my debug console output. 
```

W/System.err: java.net.SocketException: Broken pipe
W/System.err:     at java.net.SocketOutputStream.socketWrite0(Native Method)
W/System.err:     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
W/System.err:     at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
W/System.err:     at java.io.DataOutputStream.write(DataOutputStream.java:107)
W/System.err:     at org.las2mile.scrcpy.Scrcpy.startConnection(Scrcpy.java:165)
W/System.err:     at org.las2mile.scrcpy.Scrcpy.access$000(Scrcpy.java:29)
W/System.err:     at org.las2mile.scrcpy.Scrcpy$1.run(Scrcpy.java:73)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by updeshxp** [comment]
The original author has released a new version:
https://gitlab.com/las2mile/scrcpy-android
Could you Please check on the same if this issue is present.
